language: python

#sudo: false

python:
  - 3.6
  - pypy3
  
virtualenv:
  system_site_packages: true

install:
  - pip install -r requirements.txt
  - python setup.py install
  - pip install coverage

script:
  - python3 -m unittest discover -s tests

after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)