language: python

#sudo: false

python:
  - 3.6
  - pypy3

install:
  - pip install -r requirements.txt
  - pip install unittest2
  - python setup.py install

script:
  - python3 -m unittest discover -s tests

after_success:
  - codecov