language: python

#sudo: false

python:
  - 3.6
  - pypy3

install:
  - pip install -r requirements.txt
  - pip install unittest2
  - python setup.py install
  - pip install coverage

script:
#  - python3 -m unittest discover -s tests
  - coverage run -m unittest discover -s tests

after_success:
#  - codecov
  - export CODECOV_TOKEN="1430f8c9-f159-4996-8ad0-666826d9ebc5"
  - bash <(curl -s https://codecov.io/bash)